version: '3.8'

services:
  ollama:
    #build: ./ollama  # Use the custom Dockerfile in the 'ollama' directory
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama  # Persist model downloads

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  ollama_data:
  qdrant_storage:
