version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: hive-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: hive-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://hive-es:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    
  eland:
    image: docker.elastic.co/eland/eland:latest
    container_name: hive-eland
    network_mode: "bridge"
    command: ["sleep", "infinity"]

volumes:
  elasticsearch-data: